name = "shrtnr"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [
  { binding = "SHRTNR_KV", id = "c7a628ed9d7f409496e50dbd6b428739", preview_id = "c7a628ed9d7f409496e50dbd6b428739" }
]